"""fix: foreign key in students

Revision ID: 4d04ff53e151
Revises: 7be863d663da
Create Date: 2025-09-13 13:58:06.280889

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "4d04ff53e151"
down_revision = "7be863d663da"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "document_types",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "license_categories",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=50), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.add_column(sa.Column("doc_type_id", sa.Integer(), nullable=False))
        batch_op.add_column(
            sa.Column("doc_number", sa.String(length=100), nullable=False)
        )
        batch_op.create_foreign_key(None, "document_types", ["doc_type_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("doc_number")
        batch_op.drop_column("doc_type_id")

    op.drop_table("license_categories")
    op.drop_table("document_types")
    # ### end Alembic commands ###
