"""update: image_path to image_name in QuestionImage

Revision ID: 5ea263906d49
Revises: e2c520632742
Create Date: 2025-09-16 21:39:52.770833

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = "5ea263906d49"
down_revision = "e2c520632742"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_images", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_name", sa.String(length=255), nullable=False)
        )
        batch_op.drop_column("image_path")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_images", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("image_path", mysql.VARCHAR(length=255), nullable=False)
        )
        batch_op.drop_column("image_name")

    # ### end Alembic commands ###
