"""add created_at with default

Revision ID: 7be863d663da
Revises: 4aeddac232d5
Create Date: 2025-09-08 21:28:56.970482

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "7be863d663da"
down_revision = "4aeddac232d5"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column(
                "created_at",
                sa.DateTime(),
                server_default=sa.text("now()"),
                nullable=False,
            )
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("students", schema=None) as batch_op:
        batch_op.drop_column("created_at")

    # ### end Alembic commands ###
