"""fix: Enrollment as a db.Model

Revision ID: 901da3e13368
Revises: 4d04ff53e151
Create Date: 2025-09-13 20:34:47.855714

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "901da3e13368"
down_revision = "4d04ff53e151"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "enrollments",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("student_id", sa.Integer(), nullable=False),
        sa.Column("category_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["category_id"],
            ["license_categories.id"],
        ),
        sa.ForeignKeyConstraint(
            ["student_id"],
            ["students.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("document_types", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    with op.batch_alter_table("license_categories", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["name"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("license_categories", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    with op.batch_alter_table("document_types", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    op.drop_table("enrollments")
    # ### end Alembic commands ###
