"""update: Competence (parent_id)

Revision ID: 98aae8d191a4
Revises: 29b975027cd9
Create Date: 2025-10-03 13:31:36.212057

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "98aae8d191a4"
down_revision = "29b975027cd9"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_competences", schema=None) as batch_op:
        batch_op.add_column(sa.Column("parent_id", sa.Integer(), nullable=True))
        batch_op.create_foreign_key(None, "question_competences", ["parent_id"], ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("question_competences", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="foreignkey")
        batch_op.drop_column("parent_id")

    # ### end Alembic commands ###
